/* generated by scripts/build-api.mjs — do not edit */
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// api-src/v1/health.ts
var health_exports = {};
__export(health_exports, {
  default: () => health_default
});
module.exports = __toCommonJS(health_exports);

// api-src/_lib/dataset.ts
var import_promises = require("node:fs/promises");
var import_node_path = require("node:path");

// src/lib/acquisition.ts
var NO_WILD_ACQUISITION_FLOOR = 90;
function wildCatchLevel(pal) {
  const min = pal.minWildLevel;
  const max = pal.maxWildLevel;
  if (min != null && max != null) {
    return Math.round(0.65 * min + 0.35 * max);
  }
  if (max != null) return max;
  if (min != null) return min;
  return null;
}
function palAcquisitionLevel(pal) {
  return wildCatchLevel(pal);
}
function worldTreeBump(pal) {
  if (pal.isWorldTreeLocked || pal.isWorldTreeBreedable) return 25;
  if (pal.acquisitionKind === "worldTree") return 25;
  return 0;
}
function computeAcquisitionCost(pal) {
  const bump = worldTreeBump(pal);
  const level = palAcquisitionLevel(pal);
  if (level != null) {
    return level + bump;
  }
  return NO_WILD_ACQUISITION_FLOOR + pal.rarity + bump;
}
function attachAcquisitionCosts(pals) {
  for (const pal of pals) {
    pal.acquisitionCost = computeAcquisitionCost(pal);
  }
}

// src/lib/breeding.ts
var UNREACHABLE = 1e4;
function pairKey(a, b) {
  return a <= b ? `${a}|${b}` : `${b}|${a}`;
}
function assembleDataset(parts) {
  const {
    meta,
    pals,
    combos,
    byChild,
    byParent,
    specialGenders,
    mutationPassives,
    minStepEdges
  } = parts;
  const byInternalName = new Map(pals.map((p) => [p.internalName, p]));
  const byName = new Map(pals.map((p) => [p.name.toLowerCase(), p]));
  const pairToChild = /* @__PURE__ */ new Map();
  for (const [a, b, child] of combos) {
    pairToChild.set(pairKey(a, b), child);
  }
  const minSteps = Array.from(
    { length: pals.length },
    () => Array.from({ length: pals.length }, () => UNREACHABLE)
  );
  for (let i = 0; i < pals.length; i++) minSteps[i][i] = 0;
  for (const [from, to, steps] of minStepEdges) {
    minSteps[from][to] = steps;
  }
  for (const pal of pals) {
    if (!pal.acquisitionKind) {
      pal.acquisitionKind = pal.isWorldTreeLocked || pal.isWorldTreeBreedable ? "worldTree" : "wild";
    }
  }
  attachAcquisitionCosts(pals);
  return {
    meta,
    pals,
    combos,
    byChild,
    byParent,
    specialGenders,
    mutationPassives,
    minSteps,
    byInternalName,
    byName,
    pairToChild
  };
}

// api-src/_lib/dataset.ts
var cached = null;
var inflight = null;
function staticBaseUrl() {
  if (process.env.VERCEL_PROJECT_PRODUCTION_URL) {
    return `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`;
  }
  if (process.env.VERCEL_URL) {
    return `https://${process.env.VERCEL_URL}`;
  }
  return null;
}
async function readJsonFile(file) {
  const candidates = [
    (0, import_node_path.join)(process.cwd(), "public", "data", file),
    (0, import_node_path.join)(process.cwd(), "data", file)
  ];
  for (const path of candidates) {
    try {
      await (0, import_promises.access)(path);
      const raw = await (0, import_promises.readFile)(path, "utf8");
      return JSON.parse(raw);
    } catch {
    }
  }
  return null;
}
async function readJsonHttp(file, base) {
  const url = `${base.replace(/\/$/, "")}/data/${file}`;
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to fetch ${url} (${res.status})`);
  }
  return await res.json();
}
async function readJson(file) {
  const fromDisk = await readJsonFile(file);
  if (fromDisk != null) return fromDisk;
  const base = staticBaseUrl();
  if (base) return readJsonHttp(file, base);
  throw new Error(
    `Dataset file not found: ${file} (no local public/data and no VERCEL_URL)`
  );
}
async function getDataset() {
  if (cached) return cached;
  if (inflight) return inflight;
  inflight = (async () => {
    const parts = {
      meta: await readJson("meta.json"),
      pals: await readJson("pals.json"),
      combos: await readJson("combos.json"),
      byChild: await readJson("by-child.json"),
      byParent: await readJson("by-parent.json"),
      specialGenders: await readJson("special-genders.json"),
      mutationPassives: await readJson("mutation-passives.json"),
      minStepEdges: await readJson("min-steps.json")
    };
    cached = assembleDataset(parts);
    return cached;
  })();
  try {
    return await inflight;
  } finally {
    inflight = null;
  }
}
function setCors(res, req) {
  const allowed = process.env.PAL_CORS_ORIGINS?.trim();
  if (!allowed || allowed === "*") {
    res.setHeader("Access-Control-Allow-Origin", "*");
  } else {
    const origin = typeof req?.headers.origin === "string" ? req.headers.origin : "";
    const list = allowed.split(",").map((s) => s.trim()).filter(Boolean);
    if (origin && list.includes(origin)) {
      res.setHeader("Access-Control-Allow-Origin", origin);
      res.setHeader("Vary", "Origin");
    } else if (list[0]) {
      res.setHeader("Access-Control-Allow-Origin", list[0]);
      res.setHeader("Vary", "Origin");
    }
  }
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  res.setHeader(
    "Access-Control-Allow-Headers",
    "Content-Type, Authorization, x-api-key"
  );
  res.setHeader("Access-Control-Max-Age", "86400");
}
function sendJson(res, status, data, req) {
  setCors(res, req);
  res.status(status).json(data);
}
function handleOptions(req, res) {
  if (req.method === "OPTIONS") {
    setCors(res, req);
    res.status(204).end();
    return true;
  }
  return false;
}
function withApiHandler(handler2) {
  return async (req, res) => {
    try {
      await handler2(req, res);
    } catch (err) {
      const message = err instanceof Error ? err.message : "Unknown error";
      console.error("[api]", message, err);
      if (!res.headersSent) {
        sendJson(res, 500, { error: "Internal server error", message }, req);
      }
    }
  };
}

// api-src/v1/health.ts
var health_default = withApiHandler(async function handler(req, res) {
  if (handleOptions(req, res)) return;
  if (req.method !== "GET") {
    return sendJson(res, 405, { error: "GET only" }, req);
  }
  const dataset = await getDataset();
  return sendJson(
    res,
    200,
    {
      ok: true,
      service: "pal-trait-calculator-api",
      release: dataset.meta.release,
      auth: {
        postRequiresApiKey: true,
        headers: [
          "Authorization: Bearer <PAL_API_KEY>",
          "x-api-key: <PAL_API_KEY>"
        ]
      },
      limits: {
        postPerMinute: 30,
        sharePerMinute: 40,
        getPerMinute: 90,
        maxBodyBytes: 131072,
        maxTreeSteps: 20,
        maxSpecimens: 30,
        maxPathLimit: 10
      },
      endpoints: [
        "GET /api/v1/health",
        "GET /api/v1/pals?q=",
        "POST /api/v1/path/merge",
        "POST /api/v1/path/chain",
        "POST /api/v1/share",
        "GET /schema/share-v1.json"
      ]
    },
    req
  );
});
module.exports = module.exports.default ?? module.exports;
