/* generated by scripts/build-api.mjs — do not edit */
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// api-src/v1/ping.ts
var ping_exports = {};
__export(ping_exports, {
  default: () => handler
});
module.exports = __toCommonJS(ping_exports);
var import_node_fs = require("node:fs");
var import_node_path = require("node:path");
async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  if (req.method === "OPTIONS") {
    res.status(204).end();
    return;
  }
  const publicDir = (0, import_node_path.join)(process.cwd(), "public", "data");
  const dataDir = (0, import_node_path.join)(process.cwd(), "data");
  const publicData = (0, import_node_fs.existsSync)(publicDir);
  const data = (0, import_node_fs.existsSync)(dataDir);
  res.status(200).json({
    ok: true,
    ping: true,
    node: process.version,
    cwd: process.cwd(),
    hasDataDir: {
      publicData,
      data,
      files: publicData ? (0, import_node_fs.readdirSync)(publicDir).slice(0, 20) : data ? (0, import_node_fs.readdirSync)(dataDir).slice(0, 20) : []
    },
    env: {
      hasApiKey: Boolean(process.env.PAL_API_KEY),
      hasUpstashUrl: Boolean(process.env.UPSTASH_REDIS_REST_URL),
      hasUpstashToken: Boolean(process.env.UPSTASH_REDIS_REST_TOKEN),
      vercel: Boolean(process.env.VERCEL),
      vercelUrl: process.env.VERCEL_URL || null
    }
  });
}
module.exports = module.exports.default ?? module.exports;
