import * as esbuild from "esbuild";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outRoot = join(root, "api");

/** API route entrypoints → emitted CJS files under /api */
const entries = [
  "v1/health.ts",
  "v1/ping.ts",
  "v1/pals.ts",
  "v1/share.ts",
  "v1/path/chain.ts",
  "v1/path/merge.ts",
];

await rm(outRoot, { recursive: true, force: true });
await mkdir(outRoot, { recursive: true });

// Ensure Node treats emitted /api/*.js as CommonJS even if root is "type": "module".
await writeFile(
  join(outRoot, "package.json"),
  `${JSON.stringify({ type: "commonjs" }, null, 2)}\n`,
);

for (const rel of entries) {
  const infile = join(root, "api-src", rel);
  const outfile = join(outRoot, rel.replace(/\.ts$/, ".js"));
  await mkdir(dirname(outfile), { recursive: true });

  await esbuild.build({
    entryPoints: [infile],
    outfile,
    bundle: true,
    platform: "node",
    target: "node20",
    format: "cjs",
    sourcemap: false,
    logLevel: "info",
    // Keep native/optional deps that esbuild can't usefully inline.
    // Everything else (src/lib, api-src/_lib, upstash) is bundled in.
    packages: "bundle",
    banner: {
      js: "/* generated by scripts/build-api.mjs — do not edit */",
    },
    footer: {
      // Vercel Node expects the handler on module.exports, not .default.
      js: "module.exports = module.exports.default ?? module.exports;",
    },
  });

  console.log(`bundled api/${rel.replace(/\.ts$/, ".js")}`);
}

console.log("API bundles ready.");
